# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: golangid/candi-plugin
          path: candi-plugin
          token: ${{secrets.TOKEN}}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Dashboard
        run: |
          node -v
          npm -v
          npm install -g yarn@1.22.19
          yarn install
          rm -rf .env
          rm -rf .next
          yarn run build
          yarn run export
          cd external
          go get github.com/shurcooL/vfsgen
          go run -tags=dev ./asset_dashboard.go
          go mod tidy
          cp assets_dashboard_build.go /opt/assets_dashboard_build.go

      - name: Push Go Code
        run: |
          cp -RT /opt/assets_dashboard_build.go candi-plugin/task-queue-worker/dashboard/assets_dashboard_build.go
          cd candi-plugin
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "task queue worker: update dashboard\nhttps://github.com/agungdwiprasetyo/task-queue-worker-dashboard/commit/${GITHUB_SHA}"
          git push https://$USERNAME:$REPO_KEY@github.com/golangid/candi-plugin.git
        env:
          REPO_KEY: ${{secrets.TOKEN}}
          USERNAME: github-actions[bot]
